### ISSUE TITLE
Koshei the Deathless Quest

### ISSUE THREAD

**Issue by Giorox** [Giorox/Angelion-TFS-1.5-Downgrade-8.6#235]
We've had previous implementations that are going to need to be reviewed, notably:
- [ ] Check if Sweaty Cyclops enforces the 24-hour timer to give you the fixed amulet back. (#88);
- [ ] Check if the script that resets the entrance to Koshei's crypt in Darashia works (#86);
- [ ] Check if once reset, the sundial action continues to work (#5)
