### ISSUE TITLE
Review all monsters

### ISSUE THREAD

**Issue by Giorox** [Giorox/Angelion-TFS-1.5-Downgrade-8.6#83]
Review all monster's attributes:

- Health
- Experience
- Speed
- Summon and Convince costs
- Species (defines blood splatter class)
- Illusionable, Paralysable, Sense Invisible, Pushable and Pushes
- Runs on low health? If so, what health?
- Elemental Properties
- Abilities
- Loot
- Speech
- Name, description, sprite and corpse (corpse decay aswell)

The following [categories](https://tibia.fandom.com/wiki/Creatures) are to be reviewed, click on each issue link to check which monsters have been done already:
**NOTE: There will be duplicates in different categories, make sure to check them off as they come up**

- [x] Frogs (#82)
- [ ] Quara (#81)
- [ ] Archdemons (#80 )
- [ ] Demon Lords (#79)
- [ ] Demons (#78)
- [ ] Hands (#77)
- [ ] Dreamhaunters (#76)
- [ ] Imps (#75)
- [ ] The Ruthless Seven (#74)
- [ ] The Ruthless Seven Minions (#73)
- [ ] Triangle of Terror (#72)
- [ ] Bio-Elementals (#71)
- [ ] Blobs (#70)
- [ ] Cryo-Elementals (#69)
- [ ] Electro-Elementals (#68)
- [ ] Elemental Lords (#67)
- [ ] Geo-Elementals (#66)
- [ ] Hydro-Elementals (#65)
- [ ] Pyro-Elementals (#64)
- [ ] Chakoyas (#63)
- [ ] Djinn (#62)
- [ ] Dwarves (#61)
- [ ] Dworcs (#60)
- [ ] Elves (#59)
- [ ] Giants (#58)
- [ ] Goblins (#57)
- [ ] Minotaurs (#56)
- [ ] Orcs (#55)
- [ ] Trolls (#54)
- [ ] Amazons (#53)
- [ ] Barbarians (#52)
- [ ] Monks (#51)
- [ ] Necromancers (#50)
- [ ] Outlaws (#49)
- [ ] Pirates (#48)
- [ ] Sorcerers (#47)
- [ ] Voodoo Cultists (#46)
- [ ] Lycanthropes (#45)
- [ ] Annelids (#44 )
- [ ] Arachnids (#43)
- [ ] Bonelords (#42)
- [ ] Crustaceans (#41)
- [ ] Insects (#40)
- [ ] Myriapods (#39)
- [ ] Apes (#38)
- [ ] Bats (#37)
- [ ] Bears (#36)
- [ ] Canines (#35)
- [ ] Felines (#34)
- [ ] Glires (#33)
- [ ] Hyaenids (#32)
- [ ] Mustelids (#31)
- [ ] Mutated Mammals (#30)
- [ ] Ungulates (#29)
- [ ] Birds (#28)
- [ ] Machines (#27)
- [ ] Crocodillians (#26)
- [ ] Dragons (#25)
- [ ] Draken (#24)
- [ ] Hydras (#23)
- [ ] Lizards (#22)
- [ ] Serpents (#21)
- [ ] Tortoises ()
- [ ] Wyrms (#20)
- [ ] Wyverns (#19)
- [ ] Arena Bosses (#18)
- [ ] Bosses (#17)
- [ ] Event Creatures (#16)
- [ ] Shapeshifters (#15)
- [ ] Traps (#14)
- [ ] Ghosts (#13)
- [ ] Pharaos (#12)
- [ ] Skeletons (#11)
- [ ] Undead Humanoids (#10)
- [ ] Vampires (#9)
----------------------------
Migrated. Old issue:
https://api.github.com/repos/Giorox/AngelionOT-Repo/issues/227/comments

**Comment by Giorox** [comment]
Closing as unneeded to track progress.
